import {
  AudioPlayer,
  createAudioPlayer,
  setAudioModeAsync,
  setIsAudioActiveAsync,
} from 'expo-audio';

type Effect = 'point' | 'game' | 'set' | 'match' | 'undo';

// The applause is a real recording (Pixabay, free for commercial use, no
// attribution required), trimmed to three lengths. The tap and undo ticks are
// generated by scripts/generate-audio.js.
const SOURCES: Record<Effect, number> = {
  point: require('../../assets/audio/ball-hit.wav'),
  game: require('../../assets/audio/applause-game.mp3'),
  set: require('../../assets/audio/applause-set.mp3'),
  match: require('../../assets/audio/celebration.mp3'),
  undo: require('../../assets/audio/undo.wav'),
};

const VOLUMES: Record<Effect, number> = {
  point: 0.85,
  game: 0.75,
  set: 0.8,
  match: 0.9,
  undo: 0.5,
};

class SoundEffectsManager {
  private enabled: boolean = true;
  private players: Partial<Record<Effect, AudioPlayer>> = {};
  private audioModeReady = false;

  setEnabled(enabled: boolean) {
    this.enabled = enabled;
  }

  private async ensureAudioMode() {
    if (this.audioModeReady) return;
    this.audioModeReady = true;
    try {
      await setAudioModeAsync({
        // Matches are played with the ringer switch off as often as not, so
        // the score has to be audible in silent mode.
        playsInSilentMode: true,
        // Share the session rather than seizing it. Taking it exclusively made
        // each short effect tear the session down on the way out, which cut
        // the spoken score off part-way through.
        interruptionMode: 'mixWithOthers',
      });
      // Hold the session open for the life of the app so it is not torn down
      // and rebuilt around every 150ms tick.
      await setIsAudioActiveAsync(true);
    } catch (err) {
      console.warn('Audio mode error:', err);
    }
  }

  /** Warm up the session before the first point, so that one is not clipped. */
  async prepare() {
    await this.ensureAudioMode();
  }

  private getPlayer(effect: Effect): AudioPlayer {
    let player = this.players[effect];
    if (!player) {
      player = createAudioPlayer(SOURCES[effect]);
      player.volume = VOLUMES[effect];
      this.players[effect] = player;
    }
    return player;
  }

  private async play(effect: Effect) {
    if (!this.enabled) return;
    await this.ensureAudioMode();
    // Between the awaits above and the play below the user may have muted.
    if (!this.enabled) return;

    try {
      const player = this.getPlayer(effect);
      // Rewind first: a second tap should retrigger the sound, not be ignored
      // because the player is still sitting at the end of the last one.
      if (player.currentTime > 0) {
        player.pause();
        await player.seekTo(0);
        if (!this.enabled) return;
      }
      player.play();
    } catch (err) {
      console.warn('SFX playback error:', err);
    }
  }

  async playPointPop() {
    await this.play('point');
  }

  async playApplauseGame() {
    await this.play('game');
  }

  async playApplauseSet() {
    await this.play('set');
  }

  async playCelebrationMatch() {
    await this.play('match');
  }

  async playUndo() {
    await this.play('undo');
  }
}

export const soundEffects = new SoundEffectsManager();
